// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v4.25.2
// source: proto/order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "orders";

export interface Order {
  id: number;
  userId: number;
  orderStatus: string;
  totalPrice: number;
}

export interface GetOrderRequest {
  id: number;
}

export interface CreateOrderRequest {
  order: Order | undefined;
}

export interface UpdateOrderRequest {
  order: Order | undefined;
}

export interface DeleteOrderRequest {
  id: number;
}

export interface ListOrdersRequest {
}

export interface ListOrdersResponse {
  orders: Order[];
}

export const ORDERS_PACKAGE_NAME = "orders";

export interface OrderServiceClient {
  getOrder(request: GetOrderRequest): Observable<Order>;

  createOrder(request: CreateOrderRequest): Observable<Order>;

  updateOrder(request: UpdateOrderRequest): Observable<Order>;

  deleteOrder(request: DeleteOrderRequest): Observable<Order>;

  listOrders(request: ListOrdersRequest): Observable<ListOrdersResponse>;
}

export interface OrderServiceController {
  getOrder(request: GetOrderRequest): Promise<Order> | Observable<Order> | Order;

  createOrder(request: CreateOrderRequest): Promise<Order> | Observable<Order> | Order;

  updateOrder(request: UpdateOrderRequest): Promise<Order> | Observable<Order> | Order;

  deleteOrder(request: DeleteOrderRequest): Promise<Order> | Observable<Order> | Order;

  listOrders(
    request: ListOrdersRequest,
  ): Promise<ListOrdersResponse> | Observable<ListOrdersResponse> | ListOrdersResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getOrder", "createOrder", "updateOrder", "deleteOrder", "listOrders"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
